version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - redis
    command: uvicorn app.main_no:app --host 0.0.0.0 --port 8000
  redis:
    image: redis
    ports:
      - 6379:6379
